GET http://localhost:8080/secured/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhbGljZUBleGFtcGxlLmNvbSIsIm5iZiI6MTYxODYwMDQ1Miwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Im1uLWpkYmMtYXV0aCIsImxhbmd1YWdlIjoiZW4iLCJleHAiOjE2MTg2MDQwNTIsImlhdCI6MTYxODYwMDQ1MiwiaGFpcl9jb2xvciI6ImJyb3duIn0.S2_z3BfiwxcPWi4E5YxWii-2S69qMZrXpgMPRX4LHQ4